repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: poetry run ruff check .
        language: system
        types: [python]

      - id: compileall
        name: compileall
        entry: poetry run python -m compileall -q src main.py
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: poetry run pytest -q
        language: system
        types: [python]

